### ISSUE TITLE
Is there any detail installation document to this tool?

### ISSUE THREAD

**Issue by kotsachin** [MediaMath/keryxlib#51]
Hi ,

I would like to install and test this tool. I have no experience with go lang.
If there is any detail installation document for this tool, please share .

Regards,
Sachin

**Comment by kklipsch** [comment]
This isn't so much a tool as a library.  You'd use it to build a tool in go to do this work.  If you aren't comfortable with go lang this is unlikely to be helpful to you.

**Comment by bhand-mm** [comment]
If you are looking for a tool, starting with postgres 9.3 there is a tool called 'pg_xlogdump' that will give you the same information.  For 9.1 and 9.2 you can build the tool yourself from [this project](https://github.com/snaga/xlogdump).
